version: '3'

services:
    postgres:
        container_name: 'funds-service-postgres'
        build:
            context: ./.docker/postgres
            dockerfile: Dockerfile
        restart: always
        shm_size: 4g
        ports:
            - 5401:5432
        volumes:
            - "./.docker/postgres/data:/var/lib/postgresql/data:rw"
        environment:
            - POSTGRES_DB=funds-service
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=123456789
            - PGDATA=/var/lib/postgresql/data
            - POSTGRES_HOST_AUTH_METHOD=trust

    redis:
        container_name: 'funds-service-redis'
        build: .docker/redis
        ports:
            - 6301:6379
        volumes:
            - "./.docker/redis/data:/data:rw"

    php:
        build: .docker/php
        container_name: 'funds-service-php'
        volumes:
            - .:/var/www/html/funds-service
        links:
            - postgres
            - redis
        depends_on:
            - php-worker

    php-worker:
        image: php
        build: .docker/php
        container_name: 'funds-service-php-worker'
        volumes:
            - .:/var/www/html/funds-service
        links:
            - postgres
            - redis
        command: >
            bash -c "cd /var/www/html/funds-service && composer setup && php -r 'echo \"Ready to go!\n\";' && php artisan queue:work"

    nginx:
        build:
            context: .docker
            dockerfile: nginx/Dockerfile
        container_name: 'funds-service-nginx'
        ports:
            - 8001:80
        depends_on:
            - php
        volumes:
            - .:/var/www/html/funds-service

volumes:
    postgres:
        driver: local
    php:
        driver: local
    redis:
        driver: local
